var Datadescription_en = {
    legendtitle: "Legend",
    nodata: "There is no data",
    attribution: "Source",
    editButton: "Edit",
    saveButton: "Save",
    cancelButton: "Cancel",
    deleteButton: "Delete",
    addButton: "Add",
    valueexists: "Value already exists, please choose different value.",
    valuePlaceholder: "Value",
    valueTxtPlaceholder: "Color Description",
    txt_titlePlaceholder: "Title",
    txt_descPlaceholder: "Description",
    attributeexists: "Attribute already exists, please choose different attribute name.",
    addNewAttribute: "Add new attribute",
    modal_title: "New attribute",
    modal_attribute: "Attribute name",
    modal_border_color: "Color of the border",
    modal_visualise: "Visualise",
    borderColorTooltip: "Color of the border",
    attributeDeleteTooltip: "Delete attribute",
};
export default Datadescription_en;