var Mediaplayer_en = {
    playlist: 'Playlist',
    fullscreen: 'Fullscreen',
    play: 'Play',
    pause: 'Pause',
    prevtitle: 'Prev title',
    nexttitle: 'Next title',
    volume: 'Volume',
    mute: 'Mute',
    download: 'Download actual medium',
    sendcomment: 'Send comment',
    closeoverlay: 'Continue',
    remove: 'REmove from playlist',
    save: 'Save playlist',
    titlepage: 'Go to titles page',
    title: 'Title',
    title_download: 'Download this',
    artist: 'Artist',
    album: 'Album',
    license: 'License',
    info: 'Info',
    time: 'Playtime title / list',
    title_problem: 'This title is currently not available.',
    title_none: 'There is no title available.',
    anounce: 'Next you hear %title% from %artist%',
    makeoffline: 'Make playlist available offline'
};
export default Mediaplayer_en;